# Generated by Django 3.0.7 on 2020-07-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='pincode',
            field=models.IntegerField(default=778684),
            preserve_default=False,
        ),
    ]
