# Generated by Django 3.0.7 on 2020-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
