# Generated by Django 3.0.7 on 2020-07-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_review_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_count',
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
