# Generated by Django 3.0.7 on 2020-07-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
