# Generated by Django 3.1 on 2020-08-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
        ),
    ]
