# Generated by Django 3.1 on 2020-08-23 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_category1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category1',
            new_name='subcategory',
        ),
    ]
