# Generated by Django 3.1 on 2020-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20200925_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='one_day_offer',
            field=models.BooleanField(default=False),
        ),
    ]
