# Generated by Django 3.1 on 2020-09-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_one_day_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery',
        ),
    ]
