# Generated by Django 3.1 on 2020-09-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_product_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products'),
        ),
    ]
