# Generated by Django 3.1 on 2020-09-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20200930_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
